<SLButton@Button>:
    size_hint: 1,None
    height:self.texture_size[1]
    background_color: 0,0,0,0  # the last zero is the critical one, make invisible
    canvas.before:
        Color:
            rgba: (.4,.4,.4,1) if self.state=='normal' else (0,.7,.7,1)  # visual feedback of press
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [10,]
    font_size:'15sp'

<SLLabel@Label>:
    canvas.before:
        Color:
            rgba: (.4,.4,.4,1)
        Rectangle:
            pos: self.pos
            size: self.size

<SelectableLabel>:
    # Draw a background to indicate selection
    text_size: self.size
    halign: 'left'
    valign: 'middle'
    canvas.before:
        Color:
            rgba: (.7, 0.7, .7, 1) if self.selected else (.4, .4, .4, 1)
        Rectangle:
            pos: self.pos
            size: self.size
     
<starAlignBL>:
    orientation: 'vertical'
    spacing: 3
    padding: root.width*0.01

    BoxLayout:
        id: upper_pane
        orientation: 'horizontal'
        spacing: 3
        padding: 3
        canvas:
            Rectangle:
                pos: self.pos
                size: self.size
        
        BoxLayout:
            id: operations_pane
            orientation: 'vertical'
            spacing: 3
            padding: 3,3,3,3
            size_hint: None,1
            width: '200sp'
            
            SLLabel:
                id: filelist_label
                size_hint: None,None
                width: "194sp"
                height: "25sp"
                text: "Image files"
                halign: 'center'
                color: [0,0,0,1]
                font_color: .2,.3,.4,1
                font_size: '18sp'
                text_size: self.size # Set this so text will wrap

            ScrollView:
                canvas.before:
                    Color:
                        rgba: (.4,.4,.4,1)
                    Rectangle:
                        pos: self.pos
                        size: self.size
                do_scroll_x: True
                do_scroll_y: False
                RecycleView:
                    id: pics_list
                    viewclass: 'SelectableLabel'
                    data: []
                    SelectableRecycleBoxLayout:
                        default_size: None, dp(26)
                        default_size_hint: 1, None
                        size_hint_y: None
                        size_hint_x: None
                        width: "300sp"
                        height: self.minimum_height
                        orientation: 'vertical'
                        multiselect: False
                        touch_multiselect: False
            
            BoxLayout:
                size_hint:1,None
                padding: 4
                spacing: 4
                height: "25sp"
                canvas.before:
                    Color:
                        rgba: (.4,.4,.4,1)
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [10,]
                SLLabel:
                    text: "Keep interim"
                CheckBox:
                    id: keep_interim
        
            SLButton:
                text: 'Add images'
                on_release: root.show_load() 
            SLButton:
                id: focus_button
                disabled: True
                text: 'Set focal length'
                on_release: root.show_set_focal()
            SLButton:
                id: reset_button
                text: 'Reset'
                on_release: root.reset_ui()
                disabled: True
            SLButton:
                id: merge_button
                text: 'Merge'
                disabled: True
                on_release: root.show_merge()
            SLButton:
                id: save_button
                text: 'Save'
                disabled: True
                on_release: root.show_save()
        BoxLayout:
            id: render_pane
            orientation: 'vertical'
            spacing: 3
            padding: 3
            
            SLLabel:
                id: render_label
                color: [0,0,0,1]
                font_color: .2,.3,.4,1
                size_hint:1,None
                height: "25sp"
                font_size: '18sp'
                halign: 'center'
                text_size: self.size # Set this so text will wrap
                text: "Current Image"
                
            ScrollView:
                Button:
                    id: render_area
                    text: "Preview window"
                    disabled: True
                    size_hint:None,None
                    size: self.parent.size
                    on_size: root.show_on_size()
            SLLabel:
                id: focus_label
                color: [0,0,0,1]
                font_color: .2,.3,.4,1
                size_hint:1,None
                height: "25sp"
                font_size: '18sp'
                text_size: self.size # Set this so text will wrap
                text: "Focus Length:  Crop Factor: Please set focal length"
                
##    BoxLayout:
##        orientation: 'vertical'
##        size_hint: 1,None
##        height: "50sp"
##
##        Label:
##            id: progress_label
##            text: "Progress"
##            font_color: .2,.3,.4,1
##            font_size: '20sp'
##            text_size: self.size # Set this so text will wrap
##            
##        ProgressBar:
##            id: progBar
##            max:100
##            value:0
##            size_hint_y:0
##            height: 20

<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
            filters: ["*.tif","*.NEF","*.ARW"]
            path: "."
            multiselect: True

        BoxLayout:
            size_hint_y: None
            spacing: 3
            padding: 3
            height: 30
            SLButton:
                text: "Cancel"
                on_release: root.cancel()

            SLButton:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)

<MergeDialog>:
    merge_label: merge_label
    ok_button: ok_button
    BoxLayout:
        spacing: 3
        padding: 3
        size: root.size
        pos: root.pos
        orientation: "vertical"
        SLLabel:
            id: merge_label
            color: [0,0,0,1]
            font_color: .2,.3,.4,1
            font_size: '18sp'
            valign: 'top'
            text_size: self.size # Set this so text will wrap
            text: "Merging & Aligning"

        SLButton:
            id: ok_button
            text: "OK"
            size_hint:None,None
            font_size: '18sp'
            height: '20sp'
            width: '38sp'
            pos_hint: {'x':0.5}
            disabled: True
            on_release: root.cancel()


<SaveDialog>:
    text_input: text_input
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser
            path: "."
            on_selection: text_input.text = self.selection and self.selection[0] or ''

        TextInput:
            id: text_input
            size_hint_y: None
            height: 30
            multiline: False

        BoxLayout:
            size_hint_y: None
            spacing: 3
            padding: 3
            height: 30
            SLButton:
                text: "Cancel"
                on_release: root.cancel()

            SLButton:
                text: "Save"
                on_release: root.save(filechooser.path, text_input.text)


<SetFocusDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"

        GridLayout:
            cols: 2
            padding: 5
            spacing: 5
            SLLabel:
                text:"Set focal length:"
                size_hint_x: None
                width: "150sp"
            TextInput
                id: focal
                write_tab: False
                input_filter: "float"
                multiline: False
                hint_text: "Focal length"
            SLLabel:
                text:"Set crop factor:"
                size_hint_x: None
                width: "150sp"
            TextInput
                id: crop
                write_tab: False
                input_filter: "float"
                multiline: False
                hint_text: "Crop factor"

        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 3
            padding: 3
            SLButton:
                text: "Cancel"
                on_release: root.cancel()

            SLButton:
                text: "Set"
                on_release: root.save(focal.text, crop.text)
